---
title: "EDLD 651 Final Project"
author: "Jon Benedik Bunquin, Nafisul Huq, and Faria Shaikh"
format: html
editor: visual
warning: False
embed-resources: true
toc: true
---

## Imports

```{r}
#Try using echo = false so that the packages you use aren't displayed in the rendered document, maybe have them be cited at the end instead?

#Install.packages("devtools") 
#Install.packages("vdemdata")  #install.packages doesn't have/need to be included in the code chunk! You can run it in the console and then just load the package using library :)

library(vdemdata) 
library(dplyr)
library(skimr)
library(ggplot2)
vdem <- vdem
```

## Data Processing

### Data Filtering

```{r}
vdemdata <- vdem %>%
  filter(country_name == "Bangladesh" | 
           country_name == "Philippines" |
           country_name == "Pakistan" |
           country_name == "United States of America") %>%
  select(country_name, 
         year, 
         v2x_frassoc_thick,
         v2xel_frefair,
         v2x_freexp_altinf,
         v2x_elecoff,
         v2x_suffr) %>%
  filter(year >= 1971) %>% 
  rename(freedom_association=v2x_frassoc_thick,
         clean_elections=v2xel_frefair,
         freedom_expression=v2x_freexp_altinf,
         elected_index=v2x_elecoff,
         suffrage=v2x_suffr) #great use of the pipe function in this code chunk!

head(vdemdata)

```

### Data Exploration

```{r}
skim(vdemdata) #I didn't know of the skim function in R, I will be using this in the future when I want a quick glance at rows/columns and the types of variables in my dataset
```

<insert interpretation here>

### Data Cleaning

```{r}
vdemdata_long <- vdemdata %>%
  pivot_longer(
    cols = 3:5,
    names_to = 'criteria',
    values_to = 'score'
    )

head(vdemdata_long) #nice use of pivot_longer
```

## Data Analysis

### Bangladesh

```{r}
vdemdata_long %>%
  filter(country_name == 'Bangladesh') %>% 
  ggplot(aes(x = year, y = score, color = criteria)) +
  geom_point() +
  geom_line() +
  labs(title = 'Electoral Democracy in the Bangladesh from 1971 to 2022',
       subtitle = 'Trends in electoral democracy index scores over the last 50 years',
       x = 'Index Score', 
       y = 'Year',
       color = 'Index',
       caption = 'Data Source: Varieties of Democracy (https://www.v-dem.net)') +
  scale_color_manual(values = c("#d8b365", "#2c7fb8", "#5ab4ac"),
                    labels = c('Clean election', 'Freedom of association', 'Freedom of expression')) + 
  theme_minimal() +
  theme(plot.caption = element_text(hjust = 0))
#I didn't know you can only use ' for naming I have always used " so this is good to know!

#This is a really awesome graph! Great job changing the colors of the lines
  
```

### Pakistan

```{r}

vdemdata_long %>%
  filter(country_name == 'Pakistan') %>% 
  ggplot(aes(x = year, y = score, color = criteria)) +
  geom_point() +
  geom_line() + 
  labs(title = 'Electoral Democracy in the Pakistan from 1971 to 2022',
       subtitle = 'Trends in electoral democracy index scores over the last 50 years',
       x = 'Index Score',
       y = 'Year',
       color = 'Index',
       caption = 'Data Source: Varieties of Democracy (https://www.v-dem.net)') +
  scale_color_manual(values = c("#d8b365", "#2c7fb8", "#5ab4ac"),
                    labels = c('Clean election', 'Freedom of association', 'Freedom of expression')) + 
  theme_minimal() +
  theme(plot.caption = element_text(hjust = 0)) #I like how you included a link to the dataset in the caption of the graph

```

### Philippines

```{r}
vdemdata_long %>%
  filter(country_name == 'Philippines') %>% 
  ggplot(aes(x = year, y = score, color = criteria)) +
  geom_point() +
  geom_line() + 
  labs(title = 'Electoral Democracy in the Philippines from 1971 to 2022',
       subtitle = 'Trends in electoral democracy index scores over the last 50 years',
       x = 'Index Score',
       y = 'Year',
       color = 'Index',
       caption = 'Data Source: Varieties of Democracy (https://www.v-dem.net)') +
  scale_color_manual(values = c("#d8b365", "#2c7fb8", "#5ab4ac"),
                    labels = c('Clean election', 'Freedom of association', 'Freedom of expression')) + 
  theme_minimal() +
  theme(plot.caption = element_text(hjust = 0))
  
```

### United States

```{r}
vdemdata_long %>%
  filter(country_name == 'United States of America') %>% 
  ggplot(aes(x = year, y = score, color = criteria)) +
  geom_point() +
  geom_line() + 
  labs(title = 'Electoral Democracy in the USA from 1971 to 2022',
       subtitle = 'Trends in electoral democracy index scores over the last 50 years',
       x = 'Index Score',
       y = 'Year',
       color = 'Index',
       caption = 'Data Source: Varieties of Democracy (https://www.v-dem.net)') +
  scale_color_manual(values = c("#d8b365", "#2c7fb8", "#5ab4ac"),
                    labels = c('Clean election', 'Freedom of association', 'Freedom of expression')) + 
  theme_minimal() +
  theme(plot.caption = element_text(hjust = 0))
  
```

## Cross-Country Comparison

### Comparison per individual measure

```{r}

indicators = c('clean_elections' = 'Clean election', 
               'freedom_association' = 'Freedom of association', 
               'freedom_expression' = 'Freedom of expression')

vdemdata_long %>%
  ggplot(aes(y = country_name, x = score)) +
  geom_bar(stat = "summary", fill = '#008080') +
  facet_wrap(~criteria, labeller = labeller(criteria = indicators)) +
  labs(title = 'Electoral democracy indicators in Bangladesh, Pakistan, Philippines, and USA', 
       subtitle = 'Comparison of individual index scores',
       x = 'Index Score',
       y = 'Country',
       caption = 'Data Source: Varieties of Democracy (https://www.v-dem.net)') +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0),
        plot.caption = element_text(hjust = 0))

```

### Comparison of aggregated measures

```{r}
# calculate index score
vdemdata_scored <- vdemdata_long %>%
  pivot_wider( # convert the data to a wide format to convert all criteria back as columns 
    names_from = "criteria",
    values_from = "score",
  ) %>%
  mutate(electoral_democracy = (0.5 * # calculate based on VDEM formula of electoral democracy index
                                  (elected_index *
                                     clean_elections *
                                     freedom_association *
                                     freedom_expression *
                                     suffrage)) +
           (0.5 * ((.125 * elected_index) +
                     (.25*clean_elections) +
                     (.25 * freedom_association) +
                     (.125 * suffrage) +
                     (.25 * freedom_expression))))
```

### Aggregated Score Summary

```{r}

vdemdata_scored %>%
  group_by(country_name) %>%
  summarise(yearly_average = mean(electoral_democracy),
            yearly_median = median(electoral_democracy),
            sd = sd(electoral_democracy),
            min = min(electoral_democracy),
            max = min(electoral_democracy))



```

### Visualizing Aggregate Score

```{r}

vdemdata_scored %>%
  ggplot(aes(x = year, y = electoral_democracy, color = country_name)) +
  geom_point() +
  geom_line() +
  theme_minimal()

```
